# Generated by Django 4.1.1 on 2022-09-20 23:53

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import stuff_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuffUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('executor', 'Исполнитель')], max_length=10, verbose_name='Роль')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('Active', 'Активный'), ('Archive', 'Архивный')], default='Active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-status'],
            },
            managers=[
                ('objects', stuff_app.models.UserManager()),
            ],
        ),
    ]
