# Generated by Django 4.1.1 on 2022-09-21 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffusers',
            name='password',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль'),
        ),
    ]
