# Generated by Django 4.1.1 on 2022-09-21 11:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_app', '0002_alter_stuffusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffusers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
    ]
