# Generated by Django 4.1.1 on 2022-09-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_app', '0005_stuffusers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffusers',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuffusers',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuffusers',
            name='second_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
