# Generated by Django 4.1.1 on 2022-10-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0003_alter_equipments_attribute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий заявки',
                'verbose_name_plural': 'Комментарии заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('title', models.CharField(help_text='Введите название файла...', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание файла...', verbose_name='Описание')),
                ('file', models.FileField(upload_to=main_app.models.get_comment_file_path, verbose_name='Файл')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main_app.applicationcomments', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Файл комментария',
                'verbose_name_plural': 'Файлы комментарий',
                'ordering': ['-comment'],
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('subject', models.CharField(help_text='Введите тему зявки...', max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, help_text='Введите описание заявки...', verbose_name='Описание')),
                ('priority', models.CharField(choices=[('Accident', 'Авария'), ('Urgent', 'Срочно'), ('Planned', 'Планово')], help_text='Выберите приоритет заявки...', max_length=10, verbose_name='Приоритет')),
                ('type', models.CharField(choices=[('Planned', 'Плановая'), ('Unplanned', 'Внеплановая')], help_text='Выберите тип заявки...', max_length=15, verbose_name='Тип')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('At work', 'В работе'), ('Postponed', 'Отложена'), ('Solved', 'Решена'), ('Closed', 'Закрыта')], help_text='Выберите статус заявки...', max_length=25, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('closing_date', models.DateTimeField(verbose_name='Дата закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(help_text='Выберите клиента...', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='client_app.clients', verbose_name='Клиент')),
                ('contact_person', models.ForeignKey(help_text='Выберите котактное лицо...', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='client_app.contactpersons', verbose_name='Котактное лицо')),
                ('contract', models.ForeignKey(help_text='Выберите договор...', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='client_app.contracts', verbose_name='Договор')),
                ('equipment', models.ManyToManyField(help_text='Выберите оборудование...', related_name='applications', to='client_app.equipments', verbose_name='Оборудование')),
                ('executor', models.ForeignKey(help_text='Выберите исполнителя...', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('title', models.CharField(help_text='Введите название файла...', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание файла...', verbose_name='Описание')),
                ('file', models.FileField(upload_to=main_app.models.get_application_file_path, verbose_name='Файл')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main_app.applications', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
                'ordering': ['-application'],
            },
        ),
        migrations.AddField(
            model_name='applicationcomments',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.applications', verbose_name='Заявка'),
        ),
    ]
