# Generated by Django 4.1.1 on 2022-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsfiles',
            options={'ordering': ['-comment'], 'verbose_name': 'Файл комментария', 'verbose_name_plural': 'Файлы комментариев'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('At work', 'В работе'), ('Postponed', 'Отложена'), ('Solved', 'Решена'), ('Closed', 'Закрыта')], default='New', help_text='Выберите статус заявки...', max_length=25, verbose_name='Статус'),
        ),
    ]
